# Generated by Django 5.2.5 on 2025-11-12 05:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tipo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento'), ('DAÑADA', 'Dañada'), ('BAJA', 'Dada de Baja')], default='DISPONIBLE', max_length=20)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'db_table': 'herramienta',
                'ordering': ['nombre', 'marca'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(choices=[('UND', 'Unidad'), ('M', 'Metro'), ('M2', 'Metro Cuadrado'), ('M3', 'Metro Cúbico'), ('KG', 'Kilogramo'), ('L', 'Litro'), ('SACO', 'Saco')], default='UND', max_length=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_minimo', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('proveedor', models.CharField(blank=True, max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'material',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor de Obra'), ('BODEGUERO', 'Bodeguero'), ('OBRERO', 'Obrero')], default='OBRERO', max_length=20, verbose_name='Rol')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('CENTRAL', 'Bodega Central'), ('OBRA', 'Bodega de Obra')], default='OBRA', max_length=20)),
                ('direccion', models.CharField(max_length=300)),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('capacidad_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Capacidad (m³)')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('encargado', models.ForeignKey(limit_choices_to={'rol': 'BODEGUERO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodegas_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'db_table': 'bodega',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Obra')),
                ('direccion', models.CharField(max_length=300)),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField()),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PLANIFICACION', 'Planificación'), ('EN_CURSO', 'En Curso'), ('PAUSADA', 'Pausada'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PLANIFICACION', max_length=20)),
                ('presupuesto_estimado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(limit_choices_to={'rol': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_supervisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'db_table': 'obra',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRANSFERENCIA', 'Transferencia'), ('AJUSTE', 'Ajuste de Inventario'), ('DEVOLUCION', 'Devolución')], max_length=20)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('motivo', models.TextField(blank=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('bodega_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_entrada', to='admApp.bodega')),
                ('bodega_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_salida', to='admApp.bodega')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admApp.material')),
                ('usuario_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(blank=True, help_text='Obra a la que se destina el material', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admApp.obra')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimiento_inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddField(
            model_name='bodega',
            name='obra',
            field=models.ForeignKey(blank=True, help_text='Solo para bodegas de obra', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='admApp.obra'),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('horas_estimadas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('horas_reales', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='admApp.obra')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividad',
                'ordering': ['obra', 'fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ObraObrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin_asignacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admApp.obra')),
            ],
            options={
                'verbose_name': 'Asignación Obra-Obrero',
                'verbose_name_plural': 'Asignaciones Obra-Obrero',
                'db_table': 'obra_obrero',
            },
        ),
        migrations.CreateModel(
            name='Obrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('obras_asignadas', models.ManyToManyField(related_name='obreros', through='admApp.ObraObrero', to='admApp.obra')),
                ('usuario', models.OneToOneField(limit_choices_to={'rol': 'OBRERO'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obrero',
                'verbose_name_plural': 'Obreros',
                'db_table': 'obrero',
            },
        ),
        migrations.AddField(
            model_name='obraobrero',
            name='obrero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admApp.obrero'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion_estimada', models.DateField()),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DEVUELTO', 'Devuelto'), ('EXTRAVIADO', 'Extraviado'), ('DAÑADO', 'Dañado')], default='ACTIVO', max_length=20)),
                ('observaciones_prestamo', models.TextField(blank=True)),
                ('observaciones_devolucion', models.TextField(blank=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admApp.bodega')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admApp.herramienta')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admApp.obra')),
                ('obrero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='admApp.obrero')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'db_table': 'prestamo',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='InventarioHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_herramientas', to='admApp.bodega')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admApp.herramienta')),
            ],
            options={
                'verbose_name': 'Inventario de Herramienta',
                'verbose_name_plural': 'Inventarios de Herramientas',
                'db_table': 'inventario_herramienta',
                'unique_together': {('bodega', 'herramienta')},
            },
        ),
        migrations.CreateModel(
            name='InventarioMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_materiales', to='admApp.bodega')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admApp.material')),
            ],
            options={
                'verbose_name': 'Inventario de Material',
                'verbose_name_plural': 'Inventarios de Materiales',
                'db_table': 'inventario_material',
                'unique_together': {('bodega', 'material')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='obraobrero',
            unique_together={('obra', 'obrero')},
        ),
    ]
